studybudy/base/urls.py
from django.urls import path
from . import views

app_name = "base"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_page, name="logout"),
    path("room/<str:pk>", views.room, name="room"),
    path("create-room/", views.create_room, name="create-room"),
    path("update-room/<str:id>", views.update_room, name="update-room"),
    path("delete-room/<str:id>", views.delete_room, name="delete-room"),
]

studybudy/studybudy/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
]

studybudy/base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
        


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    # participant =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["-updated", "-created"]            
    
    def __str__(self):
        return self.name
    

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, null=False, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
         return self.body[0:50]
    

studybudy/base/forms.py
from django.forms import ModelForm
from .models import Room


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = "__all__"
        
        
                    

studybudy/base/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required 
from .models import Room, Topic
from django.contrib.auth.models import User
from .forms import RoomForm

# Create your views here.

# rooms = [ 
#          {"id": 1, "name": "Learn Pyhton",},
#          {"id": 2, "name": "Learn CSS",},
#          {"id": 3, "name": "Learn HTML",},
#          {"id": 4, "name": "Learn JS",},
#          ]

def login_page(request,):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
     
        
        try:
          user = User.objects.get(username=username)
        except:
            messages.error(request, "User does not exist")
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect("base:home")
    context = {}
    return render(request, "base/login_register.html", context )
    

def logout_page(request):
    logout(request)
    return redirect("base:home")
    


def home(request):
    q = request.GET.get("q") if request.GET.get("q") else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains = q) |
        Q(name__icontains = q) |
        Q(description__icontains = q)
        
        )
    rooms_count = rooms.count()
    topics = Topic.objects.all()
    context = { "rooms": rooms, "topics": topics, "rooms_count": rooms_count} 
    return render(request, "base/home.html", context)


def room(request, pk):
    # get_room_by_id = [ room  for room in rooms if str(room["id"]) == pk]
    # room = get_room_by_id[0] if get_room_by_id else None
    # context = None
    # try:
    #   room = Room.objects.get(id=pk)
    #   context = { "room": room } if room else None
    # except :
    #   print('No item matched')
  
    room = get_object_or_404(Room, pk=pk)
    context = { "room": room }
  
    return render(request, "base/room.html", context)

@login_required(login_url="base:login")
def create_room(request):
    form = RoomForm()
    
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect("base:home")
        
    context = { "form" : form }
    return render(request, "base/room_form.html", context )

@login_required(login_url="base:login")
def update_room(request, id):
    room = Room.objects.get(id=id)
    form = RoomForm(instance=room)
    if request.user is not room.host:
        return HttpResponse("You are allowed here")
    
    
    if request.POST:
        form = RoomForm(request.POST, instance=room)
        
        if form.is_valid:
            form.save()       
            return redirect("base:home")
        
    context = {"form": form}
    return render(request, "base/room_form.html", context)
    
@login_required(login_url="base:login")
def delete_room(request, id):
    room = Room.objects.get(id=id)
    
    if request.method == "POST":
        print(request.user, room.host)
        if request.user == room.host:
            room.delete()
            return redirect("base:home")
        else:       
            return HttpResponse("You are not allowed here")    
    return render(request, "base/delete.html", {"obj":room})
    

studybudy/base/templates/base/delete.html
{% extends 'main.html' %} {% block content %}
<form method="POST" action="">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{obj}}"?</p>
  <a href="{{request.META.HTTP.REFERER}}">Go back</a>
  <input type="submit" value="Delete" />
</form>
{% endblock content %}

studybudy/base/templates/base/home.html
{% extends 'main.html' %} {% block content %}
<style>
  .home-container {
    display: grid;
    grid-template-columns: 1fr 3fr;
  }
</style>
<h1>Home page</h1>
<div class="home-container">
  <div class="">
    <h3>browse Topics</h3>
    <hr />
    <div>
      <a href="{% url 'base:home' %}">All</a>
    </div>
    {% for topic in topics %}
    <div>
      <a href="{% url 'base:home' %}?q={{topic.name}}">{{topic.name}}</a>
    </div>
    {% endfor %}
  </div>

  <div>
    <h5>{{rooms_count}} rooms available</h5>
    <a href="{% url 'base:create-room' %}">Create new room</a>
    <div>
      {% if rooms %} {% for room in rooms %}
      <div>
        <a href="{% url 'base:update-room' room.id %}">Update Room</a>
        <a href="{% url 'base:delete-room' room.id %}">Delete</a>
        <span>@{{room.host.username}}</span>
        <h5>
          {{room.id}} --
          <a href="{% url 'base:room' room.id %}">{{room.name}}</a>
        </h5>
        <small>{{room.topic.name}}</small>
        <hr />
      </div>
      {% endfor %} {% else %}
      <p>noo room</p>
      {% endif %} {% endblock content %}
    </div>
  </div>
</div>

studybudy/base/templates/base/login_register.html
{% extends 'main.html' %} {% block content %}
<div>
  <form action="" method="POST">
    {% csrf_token %}
    <label for="username">User Name:</label>
    <input
      type="text"
      name="username"
      id="username"
      placeholder="Enter username"
    />
    <label for="userpassword">Password:</label>
    <input
      type="text"
      name="password"
      id="password"
      placeholder="Enter password"
    />

    <input type="submit" value="login" />

    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{message}}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </form>
</div>

{% endblock content %}

studybudy/base/templates/base/room.html
{% extends 'main.html' %} {% block content %}
<h1>Room page</h1>
{% if room %}
<div>
  <h5>{{room.id}}</h5>
  <h4>{{room.name}}</h4>
  <p>{{room.description}}</p>
  <p>{{room.updated}}</p>
  <p>{{room.created}}</p>
</div>
{% else %}
<h5>No room found</h5>
{% endif %} {{pk}} {% endblock content %}

studybudy/base/templates/base/room_form.html
{% extends 'main.html' %} {% block content %}
<div>
  <form method="POST" action="">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}

studybudy/templates/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django App</title>
  </head>
  <body>
    {% include 'navbar.html' %} {% block content %} {% endblock content %}
  </body>
</html>

studybudy/templates/navbar.html
<a href="/">
  <h1>Home</h1>
</a>
<form action="{% url 'base:home' %}" method="GET">
  <input type="text" name="q" placeholder="Search Rooms..." />
</form>
{% if request.user.is_authenticated %}
<p>{{request.user}}</p>
<a href="{% url 'base:logout' %}">Logout</a>

{% else %}
<a href="{% url 'base:login' %}">Login</a>
{% endif %}
<hr />